### ISSUE TITLE
iOS web access problem

### ISSUE THREAD

**Issue by LucLN** [Manuel83/craftbeerpi3#189]
Hi,
when I access my working CBP3 via browser from an iOS device I'm not able to start/stop, modify or open the steps details in the steps-widget. All other widget and browser-access from a computer work.
Does anyone have the same problem or a solution for this?
Luc.

**Comment by lalo-uy** [comment]
Is the same on Android. The walk around is to set "show as a Desktop" in
the browser preferences

2018-05-13 7:40 GMT-03:00 LucLN <notifications@github.com>:

**Comment by LucLN** [comment]
.. so this seems to be a problem in the frame-work ..
Thanks for answering!

**Comment by perlporter** [comment]
Does anyone know how we can solve this issue?

**Comment by DrRataplan** [comment]
This issue is with the UI code, which is unfortunately not checked in. See #75 for more info.

For now, I use the 'request desktop page' functionality of Chrome for Android when I need to use a popover, and revert back to the mobile view when I just want to look at the status of the brewing process.

**Comment by HooTsBrooklyn** [comment]
I just tried to use the fermentation page via mobile and it worked for me.  Dunno if this is a brewing page only issue.

**Comment by LucLN** [comment]
yes, for me it's on the brew-page only .. 

(found some other issues in fermentation, with reference to [#186](https://github.com/Manuel83/craftbeerpi3/issues/186) )
